### ISSUE TITLE
Improved nvfan.py for older distros

### ISSUE THREAD

**Issue by cmschroeder91** [abc123me/Nividia-Fancontrol#5]
I have improved nvfan.py to work on older distros like Ubuntu 14.04. I have also fixed a bug I introduced into trySetNvidiaSetting() in my previous patch;  I misunderstood the docs the first time and older drivers are less forgiving.

Additionally, I've created a gnome .desktop file to autostart this utility.
[nvfan_patch.zip](https://github.com/abc123me/Nvidia-Fancontrol/files/3243873/nvfan_patch.zip)

**Comment by abc123me** [comment]
Its partially implemented, I already fixed the bug I think.
