### ISSUE TITLE
Invalid Syntax on both python files

### ISSUE THREAD

**Issue by one-and-only** [abc123me/Nividia-Fancontrol#6]
I tried this today to have a fan curve for my 2009 macbook's nvidia gpu which runs quite hot. When I tried to launch either of the programs, they bot have syntax errors. The output for ```main.py``` is as follows:

```Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from nvfan import *
  File "/home/antonios/Downloads/Nvidia-Fancontrol-master/nvfan.py", line 119
    if(speed < 0) speed = 0
                      ^
SyntaxError: invalid syntax 
```

the output for nvfan.py is as follows: 

```File "nvfan.py", line 119
    if(speed < 0) speed = 0
                      ^
SyntaxError: invalid syntax

```
I launched ```main.py``` first, and then ```nvfan.py```. I am not sure what is wrong. I am running Manjaro 18.04 XFCE Edition. Any help is greatly appreciated.

**Comment by abc123me** [comment]
Sorry for the issue, it's fixed now. I don't really have much time to work on this project so errors like that crop in.
