### ISSUE TITLE
KeyError: 'DISPLAY' when using Headless Ubuntu 18.04

### ISSUE THREAD

**Issue by OscarVanL** [abc123me/Nividia-Fancontrol#8]
Hi,

I'm trying to change the fan curve on my Nvidia RTX 2070 as during load it gets hot enough to thermal throttle (88C), yet the fan only runs at 59% according to `nvidia-smi`. 

When I start this tool, I get the error `KeyError: 'DISPLAY'`

Could this be because I'm using Ubuntu over SSH headless? Do you know of any workarounds?

Thanks :)

**Comment by abc123me** [comment]
it requires an X display to operate, however! You could create a virtual X session, then run it in that session.
[xvfb-run](https://manpages.ubuntu.com/manpages/trusty/man1/xvfb-run.1.html) can do this.

Edit: I haven't used this before (in a headless environment) so I won't be able to provide much help. I have used it with xpra before (for display scaling) so I might be able to provide some feedback if you have any issues using this method.

Edit: I found this on stackoverflow as well:
```sh
Xvfb :1 -screen 0 1920x1080x24+32 -fbdir /var/tmp &
export DISPLAY=:1
python3 main.py
```
