### ISSUE TITLE
Question regarding TODO: C++, C, and Assembly are for fan control scripts - not python

### ISSUE THREAD

**Issue by AlexKordic** [abc123me/Nividia-Fancontrol#9]
Hi, just took a look at the code in `nvfan.py`. I can see that subprocess is used to execute nvidia command-line tools and parse returned text.

In my experience text parsing in assembly is almost impossible and c++ is not much better, regex helps but not good enough.

Dropping text-parsing-approach may be solution to **messiness**. 

`nvidia-smi` is command-line app to query `nvml` library for you and return text. What if you use `nvml` direcly? Much of complexity may vanish.

Take a look at [my gist](https://gist.github.com/AlexKordic/65f031b708177a01a002cc19f0d7298c). No GUI, no text parsing, no x-server dependency & configuration, no virtual X display needed.

Cheers,
Alex

**Comment by abc123me** [comment]
I don't even have an NVIDIA GPU to test this with anymore, I'm gonna archive this repo, you can fork it and do whatever you want. Sorry!
